### ISSUE TITLE
Activating the update ability of mobile app

### ISSUE THREAD

**Issue by RaziaMahmodi** [AFG-Polio-Data/APMIS-Project#235] opened 2022-08-15 21:26 UTC
### Feature Description

Mobile app should automatically get updated/option for updating.

**Comment by bnygren** [comment] 2022-09-02 14:15
@ToluOlayinka What's the best way to test this? thanks.
cc: @xlg8

**Comment by bnygren** [comment] 2022-09-14 13:24
@ToluOlayinka We have not observed any updating so are waiting to close this. @RaziaMahmodi had an old version installed and hasn't received a prompt to upgrade. I installed an old .apk but, predictably, could not sign on. We will need your guidance to review and close this. Thanks.

**Comment by ToluOlayinka** [comment] 2022-09-14 14:38
@bnygren The Request to update your App Pop up would only be triggered once there is a new mobile release pushed to the servers. I guess to properly test this, we would have to wait for a mobile release. @sundayAdu am I correct?

**Comment by bnygren** [comment] 2022-09-19 12:26
@ToluOlayinka See below. Confirmed by me and @RaziaMahmodi 
![Screenshot_20220919-082254](https://user-images.githubusercontent.com/60660864/191016734-5689ec77-2a18-4962-a61c-4e434d20f846.png)

**Comment by sundayAdu** [comment] 2022-09-19 12:54
@bnygren and @RaziaMahmodi can you confirm you are logged have successfully logged into the server with the mobile app before trying to access the new server? if not, the update wont work for a fresh installation. This is what I mean:
The update only kicked in if a user have already logged into the server and start using the app... on this note, if the app or the server has a new release, the app will download and install the currect version on the fly. However,
If its a fresh installation, the app will only show the above screenshot and expect the user to download the recent apk.

**Comment by bnygren** [comment] 2022-09-19 13:06
@sundayAdu I can confirm I had logged in under 1.0.13. I believe @RaziaMahmodi was as well.

**Comment by xlg8** [comment] 2022-09-19 13:10
@sundayAdu I was previously logged into the server with the mobile app and when I opened the app, I did not get a pop up for a new apk on the server, I then went to the /download link and had to download the most recent apk and then clicked on it which asked to "Update app" instead of "Install app" and I didnt need to un-install previous app. But that is not what we want. We want the users never to have to go to /download and download the most recent apk and install it. Remember how SORMAS mobile app pops up a message when you synchonize and there is a new server apk release update, it would ask the user to click the update button to update to the latest version without logging back in. 

@RaziaMahmodi Can we quickly ask Saddam to test this with his already logged in app if he has this? But this needs to be verified. My apologies if I confused the team on what I tested. Thanks

**Comment by bnygren** [comment] 2022-09-19 13:13
@xlg8 What additional info does asking a 3rd person who is logged in provide?

**Comment by xlg8** [comment] 2022-09-19 13:19
> @xlg8 What additional info does asking a 3rd person who is logged in provide?
See @sundayAdu statement "The update only kicked in if a user have already logged into the server and start using the app... on this note, if the app or the server has a new release, the app will download and install the currect version on the fly" So I need to understand what Sunday means by "Start using the app" because we were all logged into the live server on the mobile devices but did any of us use the app? Like enter data, synchronize on the live server etc.? I didnt. 

So I also assumed you and Razia also did not enter data or synchronize for real data entry then we need a third eye to test it in the country who has entered data, synchronized with the server and see if there will be an update. I am only referring to Sunday's comment. If you or Razia already did this and it didnt work then @sundayAdu we need to fix this asap.

**Comment by bnygren** [comment] 2022-09-19 16:04
Doesn't the app sync right after logging in thus meeting the criteria above? @xlg8 or are you saying one can successfully log in and not be synched (and thus not get the update)?

**Comment by sundayAdu** [comment] 2022-09-19 17:21
As a result, a quick hotfix for this issue has been made available. We are conducting tests to verify that the upgrade will also take place even if you have not logged into the system before. Can we all test and confirm both on Live and Staging...

**Comment by sundayAdu** [comment] 2022-09-19 17:28
> @sundayAdu Also new app is not synchronizing after manual update. When you click on new form to add, the app crashes

There are a number of things that can cause this... You may want to check if the user is properly configured. As it is, we now require mobile users to have a Cluster Coordinator and Rest User roles to have access to the mobile app. However, with the new implimentation of forms limitation, users must now have access to forms before the could open it. Most of the crash that we have seen from this end however, is due to the mobile user old data, which is registered under old cluster that the user no longer has access to. The app will try to resyncronize with the server to make sure this is not a mistake, and that causes the app to reload.

**Comment by bnygren** [comment] 2022-09-19 20:08
Thanks @sundayAdu I tapped download from Live. Synchronization is running for 30+ min for me (~60Mbs).
![image](https://user-images.githubusercontent.com/60660864/191106372-6efc87dc-d43b-4873-a1ef-9735709ba620.png)

**Comment by abahsuccess** [comment] 2022-09-19 23:46
Hi @bnygren. If synchronization is running while the app is trying to download an update, it might mean the mobile device was left unattended. Try to close and restart the app. This time make sure to follow the onscreen instruction without allowing the device to sleep.

**Comment by xlg8** [comment] 2022-09-20 02:59
> Doesn't the app sync right after logging in thus meeting the criteria above? @xlg8 or are you saying one can successfully log in and not be synched (and thus not get the update)?

Yes it is possible to login to the REST API and when you sync it fails. I had to un-install and re-install the previous version 1.1.13 and now my app synchronizes but still waiting for the new hotfix app to trigger an update automatically

**Comment by bnygren** [comment] 2022-09-20 13:54
> Hi @bnygren. If synchronization is running while the app is trying to download an update, it might mean the mobile device was left unattended. Try to close and restart the app. This time make sure to follow the onscreen instruction without allowing the device to sleep.

Thanks @abahsuccess I attended the app for 10-15 minutes during the initial try. I have since restarted the app and device even, but it fails immediately with the 'app download failed' message. I also reinstalled 1.0.13, entered my login credentials, was prompted to update, and immediately get a message that download fails. We would expect that scenario to work now, right?

**Comment by bnygren** [comment] 2022-10-04 18:59
Hi @abahsuccess Both @xlg8 and I get the prompt followed by the warning below. We are then prompted for the PIN request and then the app seems to work ok. We tried 2 different devices, one connected to live and one to staging. Are you observing this? Thanks. 

![Image](https://user-images.githubusercontent.com/60660864/193903388-df283b0e-9a75-4d1b-be33-16371979f3df.png)

**Comment by abahsuccess** [comment] 2022-10-10 16:19
Hi @bnygren, @xlg8. This issue has been fixed and pushed. Kindly test on the mobile app. Thank You

**Comment by RaziaMahmodi** [comment] 2022-10-16 20:06
I tested and it seems to work for me. I'll close this issue. 
We can reopen this issue in case if it won't work.

**Comment by xlg8** [comment] 2022-10-17 13:32
@RaziaMahmodi This also worked for me when I tested it.

**Comment by RaziaMahmodi** [comment] 2024-05-14 15:46
version 33 and 34, users had to install the app. It even caused having 2 APMIS app installed on phone. 
![image](https://github.com/AFG-Polio-Data/APMIS-Project/assets/88741672/1418cc96-c7a4-4522-9b64-d80817c46b97)

**Closed** 2024-05-30 22:48 UTC
Labels: enhancement, Mobile App, SURGE, reverted
